.gradle:cache:
  image: gradle:7.6-jdk17
  variables:
    GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle
  cache:
    - key: $GRADLE_CACHE_KEY
      paths:
        - $GRADLE_USER_HOME/caches

stages:
  - publish

snapshot-publish:
  extends:
    - .gradle:cache
  stage: publish
  tags:
    - k8s
  script:
    - gradle test
    - gradle publishJavaPublicationToBjknrtRepository
  only:
    - spring-boot3