name: build and release

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew build

  test:
    needs:
      - build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle test
        run: ./gradlew test

  maven-publish:
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')

    needs:
      - test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Write secrets to file
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWD: ${{ secrets.MAVEN_PASSWD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWD: ${{ secrets.SIGNING_PASSWD }}
        run: |
          echo ossrh.username="$MAVEN_USERNAME" > local.properties
          echo ossrh.password="$MAVEN_PASSWD" >> local.properties
          echo signing.key="$SIGNING_KEY" >> local.properties
          echo signing.password="$SIGNING_PASSWD" >> local.properties

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Publish to snapshot repository
        if: github.ref == 'refs/heads/master'
        run: ./gradlew publishToSonatype

      - name: Publish to release repository
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          RELEASE: 1
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
